In [3]:
import numpy as np
import scipy as sp

In [59]:
A = np.array([[0, 1, 0],
            [1, 0, 1],
            [0, -1, -5]])
np.set_printoptions(precision=10)
lam, S = np.linalg.eig(A)
print('labmda_i = ' )
print(lam)
print('S = ' )
print(S)
print('S-1 = ' )
invS = np.linalg.inv(S);
print(invS)

D = np.dot(np.dot(invS, A), S)

D = np.around(D, decimals= 5)
print('D = ' )
print(D)
#B = A - np.diag([lam[0], lam[0], lam[0]])
#np.linalg.solve(B, [0, 0, 0])
#np.linalg.det(B)
#print(np.dot(A, v[:,1]))
#lam[1] * v[:,1]


labmda_i = 
[ 0.9190889976 -1.1378052016 -4.781283796 ]
S = 
[[ 0.7315003122 -0.648014488   0.044643312 ]
 [ 0.6723138887  0.7373142552 -0.2134523444]
 [-0.1135840142 -0.1909055067  0.9759329236]]
S-1 = 
[[ 0.7508748788  0.6901208397  0.1165924081]
 [-0.6989616827  0.7952822383  0.2059145848]
 [-0.0493356154  0.2358875783  1.0785098406]]
D = 
[[ 0.91909 -0.       0.     ]
 [ 0.      -1.13781 -0.     ]
 [-0.      -0.      -4.78128]]
